name: Mobile app build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main", "add-mobile-app-workflow" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.7.7'
          channel: 'stable'

      - name: Show toolchain versions
        run: flutter --version && flutter doctor

      - name: Download dependencies
        run: |
          cd openhaystack/openhaystack-mobile/
          flutter precache
          flutter pub get

      - name: Build
        run: |
          flutter pub run flutter_launcher_icons:main
          flutter build apk

          ls build/
          
