name: Mobile app build

on:
  push:
    branches: [ main ]
    paths:
      - openhaystack-mobile/**   
  pull_request:
    branches: [ main ]
    paths:
      - openhaystack-mobile/**

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '2.8.0'
          channel: 'stable'

      - name: Show toolchain versions
        run: java -version && flutter --version && flutter doctor

      - name: Download dependencies
        run: |
          cd openhaystack-mobile/
          flutter precache
          flutter pub get

      - name: Build
        run: |
          cd openhaystack-mobile/
          dart run flutter_launcher_icons:main
          flutter build apk

      - uses: actions/upload-artifact@v3
        with:
          name: app
          path: openhaystack-mobile/build/app/outputs/flutter-apk/app-release.apk
